config/routes.rb
Filemanager::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  get :about, :to => "home#about"
  resources :users, :only => [:index, :new, :destroy, :edit, :update]
  post "users/new", :to => "users#create", :as => "new_user"

  root :to => "home#index"

  scope "/files" do
    get "/(*dir)/", to: "directories#show", :as => "directory"
  end

  resource :file, :as => "bin"
  resources :directories, :as => "dir", :except => :show

end

app/models/directory.rb
class Directory < Node

  #TODO: validate uniqueness

  def subdirs
    Directory.where(:ancestry => File.join(*[ancestry,id.to_s].reject{ |i| i.blank? }))
  end

  def files
    Bin.where(:ancestry => File.join(*[ancestry,id.to_s].reject{ |i| i.blank? }))
  end
  
  private

  def set_ancestry
    self.ancestry = File.join(directory.id.to_s,directory.ancestry.to_s)
  end

end
# == Schema Information
# Schema version: 20120427235442
#
# Table name: nodes
#
#  id           :integer         not null, primary key
#  type         :string(255)
#  name         :string(255)
#  data         :text
#  file         :string(255)
#  directory_id :integer
#  user_id      :integer
#  ancestry     :string(255)
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#  basename     :text
#  fullname     :text
#  extension    :string(255)     default("")
#  size         :integer
#
# Indexes
#
#  index_nodes_on_ancestry  (ancestry)
#

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  before_filter do
    @root = current_user.root_dir
    @dirs = Directory.where(:user_id => current_user.id)
  end

  def new
    @basedir = Directory.find(params[:dir])
    @dir = @basedir.subdirs.new
  end

  def create
    @dir = Directory.new(params[:directory])
    if @dir.save
      redirect_to directory_path(@dir.fullname), notice: "Erfolgreich Verzeichnis angelegt"
    else
      flash.now[:alert] = "Fehler beim Verzeichnisanlegen"
      render :new 
    end
  end

  def show
    dirname = "/" + params[:dir].to_s
    @root.subtree.arrange
    @dir = @dirs.find_by_fullname(dirname)
    @nodes = @dir.children.order("type desc, name asc").page(params[:page]).per_page(10)
  end

  def edit
    @dir = Directory.find(params[:id])
  end

  def update
    @dir = Directory.find(params[:id])
    if @dir.update_attributes(params[:directory])
      redirect_to directory_path(@dir.parent.fullname.slice(1..-1)), notice: "Erfolgreich Verzeichnis bearbeitet"
    else
      flash.now[:alert] = "Fehler beim Verzeichnis bearbeiten"
      render :new 
    end
  end
end

app/helpers/directories_helper.rb
module DirectoriesHelper
  #TODO: make this work on the filesystem rather than the db
  def directory_naviation(name)
  end

  def directory_menu_items(fullname)
    split = fullname.split(/\//)
    split = (split.size == 0 ? [""] : split)
    e = Enumerator.new do |y|
      split.size.times do |i|
        y << split.take(i+1)
      end
    end
    e.inject([]) do |res,item|
      res.push( { :name => (item.last.present? ? item.last : "Home"),
                  :path => item.reject{ |i| i == ""}.join("/") } )
    end
  end
end

app/views/directories/_form.html.haml
- url = @dir.new_record? ? dir_index_path : dir_path
= simple_form_for @dir, :url => url do |f|
  = f.input :name
  = f.input :ancestry, :as => :hidden
  = f.button :submit

app/views/directories/edit.html.haml
%h2 Verzeichnis bearbeiten

= render :partial => 'form'

app/views/directories/new.html.haml
%h2 Neues Verzeichnis

= simple_form_for @dir, :url => dir_path do |f|
  = f.input :basename
  = f.input :directory_id, :as => :hidden
  = f.button :submit

app/views/directories/show.html.haml
%ul.breadcrumb
  %li
  - directory_menu_items(@dir.fullname)[0..-2].each do |item|
    %li
      = link_to item[:name], directory_path(item[:path])
      %span.divider= "/"
  - last = directory_menu_items(@dir.fullname).last
  %li
    %strong= last[:name]

= will_paginate @nodes, :previous_label => h("<"), :next_label => h(">"), :renderer => BootstrapLinkRenderer

%table.table.table-condensed
  %tr
    %th Name
    %th Dateityp
    %th Größe
  - @nodes.each do |node|
    - present node do |node_presenter|
      %tr
        %td= node_presenter.handle
        %td= node_presenter.extension
        %td= node_presenter.size
        -#%td= node_presenter.actions
        -#= link_to_folder(dir)
= link_button "Neues Verzeichnis", new_dir_path(:dir => @dir)
= link_button "Neue Datei hinzufügen", new_bin_path(:dir => @dir)