config/routes.rb
Filemanager::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  get :about, :to => "home#about"
  resources :users, :only => [:index, :new, :destroy, :edit, :update]
  post "users/new", :to => "users#create", :as => "new_user"

  root :to => "home#index"

  scope "/files" do
    get "/(*dir)/", to: "directories#show", :as => "directory"
  end

  resource :file, :as => "bin"
  resources :directories, :as => "dir", :except => :show

end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_filter :only => [:new, :edit] do
    @basedir = Directory.find(params[:dir])
  end

  def new
    @file = @basedir.files.new
  end

  def create
    @file = Bin.new(params[:bin])
    if @file.save
      redirect_to directory_path(@file.parent.fullname.slice(1..-1)), :notice => "Erfolgreich Datei erstellt"
    else
      flash.now[:alert] = "Beim Erstellen der Datei ist etwas schiefgelaufen"
      render :new
    end
  end
end

app/helpers/files_helper.rb
module FilesHelper
end

app/views/files/index.html.haml
%h1 Dateien

= will_paginate @files, :previous_label => h("<"), :next_label => h(">"), :renderer => BootstrapLinkRenderer

%table.table.table-condensed
  %tr
    %th Name
    %th Dateityp
    %th Größe
  - @files.each do |file|
    %tr
      %td= file.name
      %td= file.ext
      %td= file.size

app/views/files/new.html.haml
%h1 Neue Datei anlegen

= simple_form_for @file, :url => bin_path do |f|
  -#= f.input :data, :placeholder => "ich werde ein hash" # TODO: remove this
  = f.input :ancestry, :as => :hidden
  = f.input :file
  = f.input :file_cache, :as => :hidden
  = "zeige datei, wenn was im cache ist"
  %br/
  = f.button :submit